import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../../../src/styles/Home.module.css";
import BackArrow from "@/components/Icons/BackArrow";
import SpetialText from "../../../data/SpetialText";

import { FakesBarChart } from "@/components/FakesBarChart/FakesBarChart";
import useLangSwitcher from "../../../utils/i18n/useLangSwitcher";
import { useState, useEffect } from "react";
import dynamic from "next/dynamic";

const FakeList = dynamic(() => import("@/components/Fake/FakeList"), {
  loading: () => <p style={{ margin: "0 auto" }}>Loading...</p>,
});

const NarrativePage = () => {
  const [dataNarrative, setDataNarrative] = useState(null);
  const [isLoading, setLoading] = useState(false);

  const [tagName, setTagName] = useState("");

  const router = useRouter();
  const { locale } = router;
  const { id } = router.query;
  const { data } = useLangSwitcher();

  useEffect(() => {
    fetch(
      `https://vox-dashboard.ra-devs.tech/api/narratives?per_page=30&lang=${locale}`
    )
      .then((res) => res.json())
      .then((data) => {
        setDataNarrative(data);
        setLoading(false);
      })
      .catch((error) => {
        console.error(error);
      });
  }, [locale]);

  const narrativeDescription =
    dataNarrative &&
    // @ts-ignore
    dataNarrative.data.map((item) => {
      if (item.id == id) {
        return (
          <div key={item.id}>
            <h2 className={styles.narrativeHeading}>{item.title}</h2>
            <hr
              style={{
                height: "4px",
                background: "#FF2618",
                border: "none",
                width: "100%",
              }}
            />
            <p className={styles.caption}>
              <SpetialText name={"About_Narrative"} />:
            </p>
            <p
              key={item.id}
              className={styles.discription}
              dangerouslySetInnerHTML={{ __html: item.description }}
            />
          </div>
        );
      }
    });

  const narrativeDiscriptions: string[] = [];
  // @ts-ignore
  data.map((item) => {
    if (item.Narrative === id) {
      if (!narrativeDiscriptions.includes(item.Description)) {
        narrativeDiscriptions.push(item.Description);
      }
    }
  });

  const narrativeTags: string[] = [];
  // @ts-ignore
  data.map((item) => {
    if (item.Narrative === id) {
      // let tagItem = item.Tag.split(', ')
      if (!narrativeTags.includes(item.Tag)) {
        narrativeTags.push(item.Tag);
      }
    }
  });

  const uniqueNarrativeTags: string[] = [];

  // @ts-ignore
  const arrTagsTest = narrativeTags.map((item) => {
    return item.split(", ");
  });

  arrTagsTest.flat().map((item) => {
    if (!uniqueNarrativeTags.includes(item)) {
      uniqueNarrativeTags.push(item);
    }
  });

  const tagsList = uniqueNarrativeTags.map((tag, i) => (
    // <Link key={i} href={{ pathname: `/tag/${tag}` }}>
    <p
      key={i}
      className={tagName !== tag ? styles.tagName : styles.tagNameActive}
      onClick={() => setTagName(tag)}
    >
      #&nbsp;{tag}
    </p>
    // </Link>
  ));

  return (
    <div>
      <Head>
        <title>Propaganda Diary </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.barChartWrap}>
        <FakesBarChart />
      </div>

      <div className={styles.narrativeContent}>
        <div>
          <Link href="/narratives">
            <BackArrow />
          </Link>
        </div>
        <div>
          <>{dataNarrative && narrativeDescription}</>
        </div>
        <div className={styles.narrativeTags}>
          <p className={styles.caption}>
            <SpetialText name={"Tags"} />:
          </p>

          <div className={styles.narrativeTag}>{tagsList}</div>
        </div>

        <hr
          style={{
            height: "2px",
            background: "#cccccc",
            border: "none",
            width: "100%",
            marginBottom: "2rem",
          }}
        />
        {/* @ts-ignore */}
        <FakeList narrative={id} tagName={tagName} />
      </div>
    </div>
  );
};

export default NarrativePage;
