import Head from "next/head";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";

export default function AboutEn() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, type: "tween" }}
        className={styles.mainLeft}
      >
        <p className="c7">
          <span className="c4"></span>
        </p>
        <p className={styles.c8}>
          <span className="c4">
            Russian information strategy utilizes existing tensions by
            exaggerating disputes and disagreements between people and amplify
            popular unrest whenever possible (e.g. Russia tried to amplify
            social unrest during ‘yellow vest’ protests in France). Internal
            tensions and clashes undermine developed democracies and cause these
            countries to focus on their domestic agenda rather than trying to
            promote their values and support progress in the developing world.
            This adversely impacts countries such as Ukraine which look for
            guidance and political support from the West.
          </span>
        </p>
        <p className="c7">
          <span className="c4"></span>
        </p>
        <p className={styles.c8}>
          <span className="c4">
            The methods used by Russian propaganda are well known -
            manipulations (blurring facts with misinterpretations), presenting
            lies as ‘alternative points of view’, and highly emotional blatant
            lies that are hard to believe but easy to remember. Knowing their
            methods and narratives can help limit the consumption of fakes and
            controversies. Therefore, VoxCheck created the database of Russian
            fakes, disinformation, and propaganda in two European countries -
            Italy and Germany.
          </span>
        </p>
        <p className="c7">
          <span className="c4"></span>
        </p>
        <p className={styles.c8}>
          <span className="c4">
            We also recommend you to read additional information about Ukraine,
            Russia-Ukranian war and Russian propaganda in the next articles:{" "}
          </span>
        </p>
        <p className="c7">
          <span className="c4"></span>
        </p>
        <ol className="c5 lst-kix_wg6xnvezo99m-0 start">
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/rashism-or-why-russians-are-the-new-nazi/"
              >
                Rashism or why russians are the new Nazi
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/provocation-and-disinformation-overview/"
              >
                UPDATED. Provocation and Disinformation Overview
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/faq-on-the-russian-war-in-ukraine-what-are-we-fighting-for/"
              >
                FAQ on the Russian war in Ukraine: what are we fighting for?
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/five-failures-of-putin-s-blitzkrieg-in-ukraine/"
              >
                Five failures of putin’s blitzkrieg in Ukraine
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/three-russian-myths-that-you-should-abandon-right-away/"
              >
                Three Russian myths that you should abandon right away
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-best-macroeconomic-policy-for-russia/"
              >
                The best macroeconomic policy for Russia
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/what-makes-us-ukrainians-different-from-russians-aspirations-for-freedom-liberal-democracy-and-inclusive-society-as-the-primary-markers-for-the-ukrainian-russian-divide/"
              >
                What makes us, Ukrainians, different from Russians? Aspirations
                for freedom, liberal democracy, and inclusive society as the
                primary markers for the Ukrainian-Russian divide!
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-hague-tribunal-what-will-russia-be-tried-for-and-how-voxcheck-explains/"
              >
                The Hague Tribunal: What will russia be tried for and how?
                VoxCheck explains
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-geneva-conventions-how-russia-breaches-them-and-blames-ukraine-for-it-voxcheck-explains/&amp;sa=D&amp;source=editors&amp;ust=1652630915863120&amp;usg=AOvVaw3FAf0TQ1h05HBYKZCcN1Xi"
              >
                The Geneva Conventions: How Russia breaches them and blames
                Ukraine for it. VoxCheck explains
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/democracy-under-the-bombs/"
              >
                Democracy under the bombs
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/it-s-not-putin-it-s-russia/"
              >
                It’s not Putin, it’s Russia
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/sanctions-on-russian-oil-have-a-bite/"
              >
                Sanctions on Russian oil have a bite
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/financial-and-economic-sanctions-when-enough-is-enough/"
              >
                Financial and economic sanctions: When enough is enough?
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/stop-the-corruption-of-russian-money/"
              >
                Stop the corruption of Russian money
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/ukraine-s-no-fly-zone-does-not-require-nato-nor-a-un-security-council-resolution-it-needs-good-to-cooperate-prevent-evil-from-destroying-our-planet/"
              >
                Ukraine’s no-fly zone does not require NATO nor a UN Security
                Council Resolution: it needs good to cooperate &amp; prevent
                evil from destroying our planet
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-moral-bankruptcy-of-buying-russian-energy/"
              >
                The Moral Bankruptcy of Buying Russian Energy
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-cost-of-peace-without-a-reformed-russia-will-weigh-on-the-world-for-generations/"
              >
                The Cost of “Peace” without a reformed Russia will weigh on the
                world for generations
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/hard-truths-about-likely-outcomes-of-russia-s-attack-on-ukraine/"
              >
                Hard truths about likely outcomes of Russia’s attack on Ukraine
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/what-will-happen-to-a-defeated-russian-empire/"
              >
                What will happen to a defeated russian empire?
              </a>
            </span>
          </li>
        </ol>
        <p className="c7">
          <span className="c4"></span>
        </p>
      </motion.div>
    </div>
  );
}
