import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import { useRouter } from "next/router";
const AboutUa = dynamic(() => import('@/components/About/AboutUa'), {
  loading: () => <p>Loading...</p>,
})
// import AboutUa from "@/components/About/AboutUa";
import AboutRu from "@/components/About/AboutRu";
import AboutIt from "@/components/About/AboutIt";
import AboutDe from "@/components/About/AboutDe";
import AboutEn from "@/components/About/AboutEn";
import AboutPl from "@/components/About/AboutPl";
import AboutCs from "@/components/About/AboutCs";
import AboutSk from "@/components/About/AboutSk";
import AboutHu from "@/components/About/AboutHu";

export default function About() {
  const router = useRouter();
  const { locale } = router;

  return (
    <div>
      <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, type: "tween" }}
        className={styles.mainLeft}
      >
        {locale === "ua" && <AboutUa />}
        {locale === "it" && <AboutIt />}
        {locale === "ru" && <AboutRu />}
        {locale === "de" && <AboutDe />}
        {locale === "en" && <AboutEn />}
        {locale === "pl" && <AboutPl />}
        {locale === "cs" && <AboutCs />}
        {locale === "sk" && <AboutSk />}
        {locale === "hu" && <AboutHu />}
      </motion.div>
    </div>
  );
}
