import styles from "@/styles/Home.module.css";
import StatisticDisplay from "@/components/StatisticDisplay/StatisticDisplay";
import { commonStatistic } from "../../utils/statisticCalculate";
import Link from "next/link";
import { motion } from "framer-motion";
import Head from "next/head";
import Timeline from "@/components/BarChart/Timeline";
import YearsList from "@/components/YearsList/YearsList";
import { useEffect, useState } from "react";

import getStatisticData from "../../lib/getStatisticData";

const Archive = () => {
  const [current, setCurrent] = useState("2022");
  const [statisticData, setStatisticData] = useState(null);

  useEffect(() => {
    let isMounted = true;
    async function getNarrative() {
      const dataFetched = await getStatisticData();
      if (isMounted) {
        setStatisticData(dataFetched);
      }
    }
    getNarrative();
  }, []);

  const statisticRender =
    statisticData &&
    // @ts-ignore
    statisticData.data.map((item, i) => {
      if (current == item.year) {
        return (
          <Link key={i} href={"/month/" + item.month}>
            <StatisticDisplay
              mode="disactive"
              month={item.month}
              year={item.year}
              narratives={item.narrative}
              fakes={item.sub_narrative}
              sources={item.media}
            />
          </Link>
        );
      }
    });

  return (
    <>
      <Head>
        <title>Propaganda Diary | Archive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, type: "tween" }}
        >
          <Timeline current={current} />
          <YearsList current={current} setCurrent={setCurrent} />
        </motion.div>

        <motion.div
          className={styles.archivePage}
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, type: "tween", delay: 0.2 }}
        >
          {statisticRender}
        </motion.div>
      </main>
    </>
  );
};

export default Archive;
