import Head from "next/head";
import styles from "@/styles/Home.module.css";

import dynamic from "next/dynamic";

const LatestNarratives = dynamic(
  () => import("@/components/LatestNarratives/LatestNarratives"),
  {
    loading: () => <p>Loading...</p>,
  }
);

const StatisticDisplay = dynamic(
  () => import("@/components/StatisticDisplay/StatisticDisplay"),
  {
    loading: () => <p>Loading...</p>,
  }
);

import { motion } from "framer-motion";

import { uniqueNarrativesEn } from "../../utils/statisticCalculate";
import { uniqueFakesEn } from "../../utils/statisticCalculate";
import { uniqueSourcesEn } from "../../utils/statisticCalculate";
import Link from "next/link";

import Timeline from "@/components/BarChart/Timeline";
import { useState } from "react";
import FivePopNarratives from "@/components/LatestNarratives/FivePopNarratives";

export default function Home() {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [current, setCurrent] = useState("2022");
  return (
    <>
      <Head>
        <title>Propaganda Diary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, type: "tween" }}
        >
          <Timeline current={current} />
          <div className={styles.yearsWrap}>
            <p
              className={current === "2022" ? styles.yearActive : styles.year}
              onClick={() => setCurrent("2022")}
            >
              2022
            </p>
            <p
              className={current === "2023" ? styles.yearActive : styles.year}
              onClick={() => setCurrent("2023")}
            >
              2023
            </p>
          </div>
        </motion.div>
        {/* <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, type: "tween" }}
        >
          <BarChartCurrent />
        </motion.div> */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, delay: 0.3, type: "tween" }}
        >
          <Link href="/archive">
            <StatisticDisplay
              mode="active"
              month="General_statistics"
              narratives={33}
              fakes={325}
              sources={93}
            />
          </Link>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, delay: 0.5, type: "tween" }}
        >
          <FivePopNarratives />
        </motion.div>
      </main>
    </>
  );
}
