import Head from "next/head";
import styles from "@/styles/Home.module.css";

import dynamic from "next/dynamic";

const LatestNarratives = dynamic(
  () => import("@/components/LatestNarratives/LatestNarratives"),
  {
    loading: () => <p>Loading...</p>,
  }
);

const StatisticDisplay = dynamic(
  () => import("@/components/StatisticDisplay/StatisticDisplay"),
  {
    loading: () => <p>Loading...</p>,
  }
);

import { motion } from "framer-motion";

import Link from "next/link";

import Timeline from "@/components/BarChart/Timeline";
import { useEffect, useState } from "react";
import FivePopNarratives from "@/components/LatestNarratives/FivePopNarratives";

import getNarrativeCommonStatistic from "../../lib/getNarrativeCommonStatistic";
import getSubNarrativeCommonStatistic from "../../lib/getSubNarrativeCommonStatistic";

import { uniqueFakes, uniqueNarratives } from "../../utils/statisticCalculate";

export default function Home() {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [current, setCurrent] = useState("2022");
  const [narrativeStatisticData, setNarrativeStatisticData] = useState(0);
  const [subNarrativeStatisticData, setSubNarrativeStatisticData] = useState(0);

  useEffect(() => {
    let isMounted = true;
    async function getNarrativeStatistic() {
      const satisticData = await getNarrativeCommonStatistic();
      if (isMounted) {
        setNarrativeStatisticData(satisticData);
      }
    }
    getNarrativeStatistic();

    async function getSubNarrativeStatistic() {
      const satisticData = await getSubNarrativeCommonStatistic();
      if (isMounted) {
        setSubNarrativeStatisticData(satisticData);
      }
    }
    getSubNarrativeStatistic();
    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <>
      <Head>
        <title>Propaganda Diary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, type: "tween" }}
        >
          <Timeline current={current} />
          <div className={styles.yearsWrap}>
            <p
              className={current === "2022" ? styles.yearActive : styles.year}
              onClick={() => setCurrent("2022")}
            >
              2022
            </p>
            <p
              className={current === "2023" ? styles.yearActive : styles.year}
              onClick={() => setCurrent("2023")}
            >
              2023
            </p>
          </div>
        </motion.div>
        {/* <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, type: "tween" }}
        >
          <BarChartCurrent />
        </motion.div> */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, delay: 0.3, type: "tween" }}
        >
          <Link href="/archive">
            <StatisticDisplay
              mode="active"
              month="General_statistics"
              narratives={
                narrativeStatisticData &&
                // @ts-ignore
                narrativeStatisticData.meta.total
              }
              fakes={
                subNarrativeStatisticData &&
                // @ts-ignore
                subNarrativeStatisticData.meta.total
              }
              sources={93}
            />
          </Link>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, delay: 0.5, type: "tween" }}
        >
          <FivePopNarratives />
        </motion.div>
      </main>
    </>
  );
}
