import Head from "next/head";
import styles from "../styles/Home.module.css";
import PolandLists from "../components/Lists/PolandLists";
import { useState } from "react";

export default function ListsPage() {
  const [country, setCountry] = useState("poland");
  return (
    <>
      <Head>
        <title>Propaganda Diary | White & Black Lists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.listCountryWrap}>
        <p className={styles.listsDiscr}>
          Ресурси у білому списку – це якісні джерела, які надають достовірну
          інформацію про зовнішню та внутрішню політику України. Натомість
          джерела з чорного списку регулярно поширюють фейкові наративи про
          Україну.
        </p>
        <ul className={styles.listCountry}>
          <li
            className={country === "poland" ? styles.activeCountry : ""}
            onClick={() => setCountry("poland")}
          >
            Польща
          </li>
          <li
            className={country === "slovak" ? styles.activeCountry : ""}
            onClick={() => setCountry("slovak")}
          >
            Словаччина
          </li>
          <li
            className={country === "czech" ? styles.activeCountry : ""}
            onClick={() => setCountry("czech")}
          >
            Чехія
          </li>
          <li
            className={country === "hungary" ? styles.activeCountry : ""}
            onClick={() => setCountry("hungary")}
          >
            Угорщина
          </li>
          <li
            className={country === "germany" ? styles.activeCountry : ""}
            onClick={() => setCountry("germany")}
          >
            Німеччина
          </li>
          <li
            className={country === "italy" ? styles.activeCountry : ""}
            onClick={() => setCountry("italy")}
          >
            Італія
          </li>
        </ul>
      </div>
      <div className={styles.listsPageWrap}>
        <div>
          {country === "poland" && <PolandLists country="Польща" />}
          {country === "slovak" && <PolandLists country="Словаччина" />}
          {country === "czech" && <PolandLists country="Чехія" />}
          {country === "hungary" && <PolandLists country="Угорщина" />}
          {country === "germany" && <PolandLists country="Німеччина" />}
          {country === "italy" && <PolandLists country="Італія" />}
        </div>
      </div>
    </>
  );
}
