import styles from "@/styles/Home.module.css";
import Head from "next/head";
import dynamic from "next/dynamic";
import { FakesBarChart } from "@/components/FakesBarChart/FakesBarChart";

const AllNarratives = dynamic(() => import('@/components/LatestNarratives/AllNarratives'), {
  loading: () => <p>Loading...</p>,
})
// import AllNarratives from "@/components/LatestNarratives/AllNarratives";

const Narratives = () => {
  return (
    <>
      <Head>
        <title>Propaganda Diary | All Narratives</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.barChartWrap}>
        <FakesBarChart />
      </div>
      <div className={styles.allNarrativesWrap}>
        <AllNarratives />
      </div>
    </>
  );
};

export default Narratives;
