import styles from "@/styles/Home.module.css";
import Head from "next/head";

import AllNarratives from "@/components/LatestNarratives/AllNarratives";
import { FakesBarChart } from "@/components/FakesBarChart/FakesBarChart";

const Narratives = () => {
  return (
    <>
      <Head>
        <title>Propaganda Diary | All Narratives</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.allNarrativesWrap}>
        <FakesBarChart />
      </div>
      <div className={styles.allNarrativesWrap}>
        <AllNarratives />
      </div>
    </>
  );
};

export default Narratives;
