// @ts-nocheck
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import YearsList from "@/components/YearsList/YearsList";
import MonthsList from "@/components/MonthsList/MonthsList";
import CountryList from "@/components/CountryList/CountryList";
import { useEffect, useState } from "react";

import getReportData from "../../lib/getReportData";
import { useRouter } from "next/router";

export default function MethodEn() {
  const router = useRouter();
  const { locale } = router;
  const [current, setCurrent] = useState("2022");
  const [currentMonth, setCurrentMonth] = useState(1);
  const [country, setCountry] = useState("Польща");

  const [reportData, setReportData] = useState(null);

  useEffect(() => {
    let isMounted = true;
    async function getData() {
      const dataFetched = await getReportData(locale);
      if (isMounted) {
        setReportData(dataFetched);
      }
    }
    getData();
  }, [locale]);

  const reportDataRender =
    reportData &&
    reportData.data.map((item) => {
      return (
        <div key={item.id} style={{ width: "100%" }}>
          <h1 style={{ textAlign: "center", textTransform: "uppercase" }}>
            {item.title}
          </h1>
          <p dangerouslySetInnerHTML={{ __html: item.content }} />
        </div>
      );
    });

  return (
    <div>
      <Head>
        <title>Propaganda Diary | Reports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, type: "tween" }}
        className={styles.main}
      >
        <YearsList current={current} setCurrent={setCurrent} />
        <MonthsList current={currentMonth} setCurrent={setCurrentMonth} />
        <hr
          style={{
            height: "2px",
            background: "#FF2618",
            border: "none",
            width: "100%",
            margin: "2rem 0",
          }}
        />
        {/* <CountryList country={country} setCountry={setCountry} /> */}
      </motion.div>
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, type: "tween" }}
        className={styles.mainLeft}
      >
        {reportDataRender}
      </motion.div>
    </div>
  );
}
