import Search from "@/components/Search/Search";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import Head from "next/head";

const search = () => {
  return (
    <>
      <Head>
        <title>Propaganda Diary | Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <motion.div
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, type: "tween" }}
      className={styles.mainLeft}
    >
      <Search />
    </motion.div>
    </>
  );
};

export default search;
